from tkinter import *
root=Tk()
root.geometry('500x500')
root.title("Language Page")
frame_language=Frame(root,height=500,width=500,bg='gray')
frame_language.pack()
picture_language = PhotoImage(file="img_3.png")
label=Label(frame_language,image=picture_language)
label.place(x=0,y=0,relheight=1,relwidth=1)

hindi=Checkbutton(label,text="Hindi", bg='#ffffff', font=('calibre', 20, 'bold'))
hindi.place(x=40,y=130,height=30,width=160)
english=Checkbutton(label,text="English",bg='#ffffff',font=('calibre', 20, 'bold'))
english.place(x=250,y=130,height=30,width=160)
punjabi=Checkbutton(label,text="Punjabi",bg='#ffffff',font=('calibre', 20, 'bold'))
punjabi.place(x=55,y=210,height=30,width=160)
others=Checkbutton(label,text="Others",bg='#ffffff',font=('calibre', 20, 'bold'))
others.place(x=250,y=210,height=30,width=160)
label_heading=Label(label,text="Choose your language",bg='#ffffff',font=('calibre',20, 'bold',"underline"))
label_heading.place(x=45,y=30,height=50,width=400)
root.mainloop()